baseurl = "http://www.lastletterdesign.com/"
languageCode = "en-us"
title = "Portfolio | Ashley Kolodziej - Boston Freelance Web Designer"
preserveTaxonomyNames = "true"
pluralizeListTitles = "false"
disableSitemap = "true"
googleAnalytics = "UA-6956431-2"

[params]
  author = "Ashley Kolodziej"
  description = "I shape the direction of theme and product frameworks, prototype, design, and test user interfaces, and teach other people how to do things I'm passionate about."
  site_description = "I shape the direction of theme and product frameworks, prototype, design, and test user interfaces, and teach other people how to do things I'm passionate about."
  og_image = ["http://lastletterdesign.com/css/opengraph.jpg"]
[social]
  facebook        = "ashleykolodziej"
  facebook_admin  = ""
  facebook_app_id = "261546164307190"
