# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "[Ashleykolodziej]"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://ashleykolodziej.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Ashley Kolodziej"
  homepage = "ashleykolodziej.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
